---
title: ""
output: html_document
---

<h2>2K1-in-Silico</h2>
<p><a target="_blank" href="https://GaryKing.org">Gary King</a> and <a target="_blank" href="https://ZagrebMukerjee.com">Zagreb Mukerjee</a>

<p>So you want to be a social scientist, and the first course they make you take is <em>statistics</em>!?  Well, statistics is about inference -- using facts you know to learn about facts you don't know -- and so perhaps you can convince yourself that it is fundamental to empirical research (really, it is!). OK, but then your social science statistics instructor makes you learn a <em>programming language</em>!?  Gosh, spending time fixing an obscure bug on line 168 of your R code, while you are supposed to be grasping deep concepts in statistical inference, feels like a massive distraction.  Learning while doing, controlling inputs and watching how outputs change, is certainly more productive than merely consulting a static textbook but, until now, programming lessons wind up interrupting learning (not much different than if we made you take swimming lessons halfway through class) and well before you start to benefit.
</p>

<p>2K1-in-Silico implements two pedagogical innovations that our research shows will enable you to learn statistical inference faster and better.  First, we enable you to postpone programming lessons and still learn by doing, by giving you complete control over all inputs in a simple web interface with instant numerical and graphic results and feedback. (Learning programming, when you get to it, will be easier too after you understand inference.) Second, we provide extensive, automated in-context assistance if, when, and where you need it. Throughout, you will see little tooltips marked <b>i</b>, to click for more information (a tooltip will open automatically when its content is essential or likely to be missed). 
</p>

<p>2K1-in-Silico (presently) enables you to learn three concepts, each with its own tab at the top of the screen:</p>
<ul style = "padding-left:25px;">
<li><b>Data Generation Processes</b>, using the model of <em>probability</em>;</li>
<li><b>Likelihood</b>, an extremely widely used theory of statistical inference, one that underlies many other such theories; likelihood is almost the inverse of probability, where we observe the data and try to infer the data generation process; and</li>
<li><b>Simulation</b>, a technique that enables you (rather than some computer program) to control how statistical results are presented, so you can understand your work better and it is more impactful</li>
</ul>

<p>The app parallels some of the core, model-based content of <a target="_blank" href="https://projects.iq.harvard.edu/gov2001/">Gov 2001</a>, the first course in the Harvard Government Department's social science methods sequence (taught by Gary King). The course is open to all for credit (even those not at Harvard via the Harvard Extension School as Stat E-200). Some of you may already have taken a political science methodology, econometrics, or statistics class focused on regression - our approach covers the same concepts, but in a more general and fundamental way. </p>

<p>All the lectures, videos, and much other teaching materials, including this app, are available for other instructors and students to use in their courses as well from the course website, <a target="_blank" href="https://projects.iq.harvard.edu/gov2001/">j.mp/G2001</a>, many parts of which are linked to in the tooltips. (Thanks to generations of Gov2001 students for helping us improve the ideas behind this app.) <a target="_blank" href="https://youtu.be/qs2uCuDL2OQ?t=2416">This lecture video</a> gives an overview of the course.
</p>

<p>To learn more about 2K1-in-Silico, to send comments or suggestions, or to contribute to this open source package, see the <a target="_blank"  href = "https://projects.iq.harvard.edu/2k1-in-silico/home">app's website</a>.</p> <br>
